
# My Database configuration
default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 timeout: 20000000
 username: athira
 password: athira


development:
 <<: *default
 # database: gilauto_new 
 #database: gilauto_new_db
 database: rails_react_recipe_development 

production:
 <<: *default
 # database: gilauto_new 
 #database: gilauto_new_db
 database: rails_react_recipe_prod